import type { RawProduct } from "@/types/product";

export const mockProducts: RawProduct[] = [
  {
    no: "92011421",
    title: "무타공 욕실 코너 선반 2단 접착식 생활 수납",
    price: 4200,
    thumb: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=500&q=80",
    sellerId: "sample01",
    sellerNick: "생활공급",
    moq: 1,
    comOnly: false,
    adultOnly: false,
    lowPriceChecked: true,
    deliveryWho: "P",
    deliveryFee: 3000,
    deliveryAdd: false,
    fromOversea: false,
    url: "https://domeggook.com",
    market: { domeggook: true, supply: true }
  },
  {
    no: "92011422",
    title: "차량용 틈새 수납 포켓 컵홀더 정리함",
    price: 3100,
    thumb: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=500&q=80",
    sellerId: "sample02",
    sellerNick: "카용품랩",
    moq: 2,
    comOnly: true,
    adultOnly: false,
    lowPriceChecked: false,
    deliveryWho: "P",
    deliveryFee: 2800,
    deliveryAdd: false,
    fromOversea: false,
    url: "https://domeggook.com",
    market: { domeggook: true, supply: false }
  },
  {
    no: "92011423",
    title: "주방 싱크대 걸이형 음식물 쓰레기통 소형",
    price: 2600,
    thumb: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=500&q=80",
    sellerId: "sample03",
    sellerNick: "홈키친",
    moq: 1,
    comOnly: false,
    adultOnly: false,
    lowPriceChecked: true,
    deliveryWho: "S",
    deliveryFee: 0,
    deliveryAdd: false,
    fromOversea: false,
    url: "https://domeggook.com",
    market: { domeggook: true, supply: true }
  },
  {
    no: "92011424",
    title: "고양이 자동 장난감 충전식 움직이는 공",
    price: 7600,
    thumb: "https://images.unsplash.com/photo-1545249390-6bdfa286032f?auto=format&fit=crop&w=500&q=80",
    sellerId: "sample04",
    sellerNick: "펫도매",
    moq: 5,
    comOnly: true,
    adultOnly: false,
    lowPriceChecked: false,
    deliveryWho: "P",
    deliveryFee: 3200,
    deliveryAdd: true,
    fromOversea: false,
    url: "https://domeggook.com",
    market: { domeggook: true, supply: true }
  },
  {
    no: "92011425",
    title: "캠핑 접이식 조명 랜턴 미니",
    price: 9800,
    thumb: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=500&q=80",
    sellerId: "sample05",
    sellerNick: "아웃도어베이스",
    moq: 10,
    comOnly: false,
    adultOnly: false,
    lowPriceChecked: true,
    deliveryWho: "B",
    deliveryFee: 3500,
    deliveryAdd: true,
    fromOversea: true,
    url: "https://domeggook.com",
    market: { domeggook: true, supply: false }
  },
  {
    no: "92011426",
    title: "책상 케이블 정리 클립 실리콘 홀더 10P",
    price: 1400,
    thumb: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=500&q=80",
    sellerId: "sample06",
    sellerNick: "오피스픽",
    moq: 1,
    comOnly: false,
    adultOnly: false,
    lowPriceChecked: true,
    deliveryWho: "P",
    deliveryFee: 2500,
    deliveryAdd: false,
    fromOversea: false,
    url: "https://domeggook.com",
    market: { domeggook: true, supply: true }
  }
];
